# Generated by Django 4.1.4 on 2022-12-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("principal", "0005_banner_remove_product_price_productattribute"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="banner",
            options={"verbose_name_plural": "1. Banners"},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "2. Categories"},
        ),
        migrations.AlterModelOptions(
            name="color",
            options={"verbose_name_plural": "4. Colors"},
        ),
        migrations.AlterModelOptions(
            name="marca",
            options={"verbose_name_plural": "3. Marcas"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name_plural": "6. Productos"},
        ),
        migrations.AlterModelOptions(
            name="productattribute",
            options={"verbose_name_plural": "7. ProductAttributes"},
        ),
        migrations.AlterModelOptions(
            name="size",
            options={"verbose_name_plural": "5. Sizes"},
        ),
        migrations.AddField(
            model_name="product",
            name="is_feat_caracterico",
            field=models.BooleanField(default=False),
        ),
    ]
